name: frontend_vm_tf_code

on: 
  push:
    branches:
      - master
  workflow_dispatch: 
    inputs:
      action:
        description: "select terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Azure Login
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Install Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Create tfvars file from secret
          run: echo '${{ secrets.TF_VARS }}' > terraform.tfvars.json

        - name: Terraform Init
          run: terraform init

        # 🔹 Push pe automatically Plan chale
        - name: Terraform Plan (Push)
          if: github.event_name == 'push'
          run: terraform plan

        # 🔹 Push pe automatically Apply chale
        - name: Terraform Apply (Push)
          if: github.event_name == 'push'
          run: terraform apply -auto-approve

        # 🔹 Manual pe Apply
        - name: Terraform Apply (Manual)
          if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
          run: terraform apply -auto-approve

        # 🔹 Manual pe Destroy
        - name: Terraform Destroy (Manual)
          if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
          run: terraform destroy -auto-approve
